demoApp:
  image: iozol/springboot
  links:
    - myslqdb
  ports:
    - "8080:8080"
  volumes:
    - ./app:/app
myslqdb:
  image: mysql:5.7
  ports:
    - "3306:3306"
  volumes:
        - "./.data/db:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp